version: vISTAG1
config_name: vISTAG1/config_prep_data.yaml
dir_input: init_data/ISTAGING-v1.2
dir_output: vISTAG1/prep_data
list_covars: vISTAG1/lists/covars/list_covar_all.csv
list_ROIs: vISTAG1/lists/MUSE/list_MUSE_all.csv
list_studies_merge: vISTAG1/lists/studies/list_studies_ISTAGING.csv
roi_types:
 - MUSE
 - DLMUSE
corr_types:
 - raw
 - normICV
