version: vISTAG1
config_name: vISTAG1/config_COMBAT.yaml
list_ROIs: vISTAG1/lists/MUSE/list_MUSE_single.csv
list_derived_ROIs: vISTAG1/lists/MUSE/list_MUSE_mapping_derived.csv
sample_COMBAT_train: vISTAG1/lists/samples/COMBAT/sample_COMBAT_ISTAG_train.csv
sample_COMBAT_test: vISTAG1/lists/samples/COMBAT/sample_COMBAT_ISTAG_all.csv
roi_types:
 - MUSE
 - DLMUSE
corr_types:
 - raw
 - normICV

