version: vTest
config_name: vTest/config_Centiles.yaml
list_ROIs: vTest/lists/MUSE/list_MUSE_primary.csv
sample_Centiles_train: vTest/lists/samples/Centiles/sample_Centiles_BLSA-SHIP_train.csv
sample_Centiles_test: vTest/lists/samples/Centiles/sample_Centiles_BLSA-SHIP_test.csv
roi_types:
 - MUSE
 #- DLMUSE
corr_types:
 - raw
 #- normICV
