version: vISTAG
config_name: config_vISTAG_COMBAT.yaml
dir_input: vISTAG/prep_data/out_data
dir_output: vISTAG/COMBAT
#list_ROIs: lists/MUSE/list_MUSE_single.csv
list_ROIs: lists/MUSE/list_MUSE_primary.csv
sample_COMBAT_train: lists/samples/COMBAT/sample_COMBAT_ISTAG_train.csv
sample_COMBAT_test: lists/samples/COMBAT/sample_COMBAT_ISTAG_all.csv
roi_types:
 - MUSE
# - DLMUSE
corr_types:
 - initROIs
# - normICV
