version: vDemo
config_name: config_vDemo_prep_data.yaml
dir_input: init_data/ISTAGING-v1.2
dir_output: vDemo/prep_data
list_covars: lists/covars/list_covar_all.csv
list_ROIs: lists/MUSE/list_MUSE_single.csv
#list_ROIs: lists/MUSE/list_MUSE_primary.csv
list_studies_merge: lists/studies/list_studies_ISTAGING.csv
roi_types:
 - MUSE
 - DLMUSE
corr_types:
 - raw
 - normICV
