version: prep_data_vtest1
dir_input: init_data/ISTAGING-v1.2
dir_output: prep_data/prep_data_vtest1
list_covars: list_covar_all.csv
list_ROIs: list_MUSE_primary.csv
list_studies_merge: list_studies_merge.csv
roi_types:
 - MUSE
corr_types:
 - raw
 - normICV
