version: vDemo
config_name: config_vDemo_Centiles.yaml
dir_input: vDemo/prep_data
dir_output: vDemo/Centiles
list_ROIs: lists/MUSE/list_MUSE_single.csv
#list_ROIs: lists/MUSE/list_MUSE_primary.csv
sample_Centiles_train: lists/samples/Centiles/sample_Centiles_BLSA-SHIP_train.csv
sample_Centiles_test: lists/samples/Centiles/sample_Centiles_BLSA-SHIP_test.csv
roi_types:
 #- MUSE
 - DLMUSE
corr_types:
 - raw
 #- normICV
