version_config: v1.1
subsample_num: 1000
subsample_list_study: ../../config/subsample_list_studies.csv
list_rois_all: ../../config/list_MUSE_allROI.csv
list_rois_single: ../../config/list_MUSE_singleROI.csv
list_rois_composite: ../../config/list_MUSE_compositeROI.csv
list_rois_primary: ../../config/list_MUSE_primaryROI.csv
list_rois_short: ../../config/list_MUSE_shortROI.csv
list_studies_ISTAGING: ../../config/list_studies_ISTAGING.csv
list_studies_merge: ../../config/list_studies_merge.csv
list_SPARE: ../../config/list_SPARE-models.csv
list_demog_normalization: ../../config/list_demog_normalization.csv
