version: vISTAG-v2.0
config_name: config_vISTAG-v2.0_prep_data.yaml
dir_input: init_data/ISTAGING-v2.0
dir_output: vISTAG-v2.0/prep_data
list_covars: lists/covars/list_covar_all.csv
list_ROIs: lists/MUSE/list_MUSE_all.csv
#list_ROIs: lists/MUSE/list_MUSE_primary.csv
list_studies_merge: lists/studies/list_studies_ISTAG-v2.0.csv
roi_types:
 - MUSE
corr_types:
 - initROIs
 - normICV
