version: v_test
version_data_prep: v_test
list_covar_all: list_covar_all.csv
list_MUSE_all: list_MUSE_all.csv
list_studies_merge: list_studies_merge.csv
roi_types:
 - MUSE
corr_types:
 - raw
 - normICV
