version: vISTAG-v2.0
config_name: config_vISTAG-v2.0_COMBAT.yaml
dir_input: vISTAG-v2.0/prep_data/out_data
dir_output: vISTAG-v2.0/COMBAT
list_ROIs: lists/MUSE/list_MUSE_single.csv
#list_ROIs: lists/MUSE/list_MUSE_primary.csv
list_derived_ROIs: lists/MUSE/list_MUSE_mapping_derived.csv
sample_COMBAT_train: lists/samples/COMBAT/sample_COMBAT_ISTAG-v2.0_train.csv
sample_COMBAT_test: lists/samples/COMBAT/sample_COMBAT_ISTAG-v2.0_test.csv
roi_types:
 - MUSE
corr_types:
 - initROIs
