version: vISTAG
config_name: config_vISTAG_prep_data.yaml
dir_input: init_data/ISTAGING-v1.2
dir_output: vISTAG/prep_data
list_covars: lists/covars/list_covar_all.csv
list_ROIs: lists/MUSE/list_MUSE_all.csv
#list_ROIs: lists/MUSE/list_MUSE_primary.csv
list_studies_merge: lists/studies/list_studies_ISTAGING.csv
roi_types:
 - MUSE
 - DLMUSE
corr_types:
 - initROIs
 - normICV
