'''
Snakemake file for NiChart MRI processing workflow
 
Input data: MRI images with consistent file suffixes organized 
in folder structure: data/MRI/{study}/{mrid}/{mrid}{file_suffix}    
'''

configfile: "./config/config.yaml"
workdir: '.'

rule ALL:
    input: 
        expand("../../data/DLMUSE/{study}/{study}_DLMUSE.csv", study=['IXI', 'OASIS3'])

def get_in_files(wildcards):
    '''
    Returns a list of image files inside the input folder
    '''
    in_files = glob_wildcards("../../data/MRI/" + wildcards.study + "/{fname}.nii.gz")
    in_paths = ['../../data/MRI/' + wildcards.study + '/' + x + '.nii.gz' for x in in_files.fname]
    return in_paths
       
rule nichart_dlmuse:
    '''
    Rule to run DLMUSE for the study
    '''
    input:
        get_in_files
    output:
        "../../data/DLMUSE/{study}/{study}_DLMUSE.csv"
    resources:
        cpus_per_task=8,
        mem_mb=32000,
        slurm_extra="--ntasks-per-node=4"
    shell:
        "bash ./utils/run_nichart_dlmuse_study.sh {wildcards.study} {output} {input}"
