## Workflow for selecting a smaller sample for large studies (e.g. UKBIOBANK)

report: "report/workflow.rst"

configfile: "../../config/config.yaml"

###################################
## Rules
rule ALL:
    input:expand("../../data/data_subsampled/UKBIOBANK-B1/UKBIOBANK-B1_{dtype}.csv", dtype = ['DemogClin', 'MUSE', 'DLMUSE'])

rule select_sample_ukbb:
    input:
        "../../data/init_data_istaging/DLMUSE/UKBIOBANK_DLMUSE.csv",
    output:
        "../../data/data_subsampled/UKBIOBANK-B1/UKBIOBANK-B1_selMRIDs.csv"
    params:
        num_sample = '8000',
        out_vars = 'MRID',
    shell:
        "python ./utils/util_subsample_data.py {input} {params} {output}"

rule filter_data_ukbb:
    input:
        in_csv="../../data/init_data_istaging/{dtype}/UKBIOBANK_{dtype}.csv",
        in_list="../../data/data_subsampled/UKBIOBANK-B1/UKBIOBANK-B1_selMRIDs.csv"
    output:
        "../../data/data_subsampled/UKBIOBANK-B1/UKBIOBANK-B1_{dtype}.csv"
    params:
        key_var = 'MRID',
    shell:
        "python ./utils/util_filter_to_subsampled.py {input} {params} {output}"
