'''
Snakemake file for NiChart Data Consolidation
 
Input data: MRI and clinical csv files organized as: 
 data/NiChart/{Clinical|MRI}/{study}{file_suffix}    
'''

## FIXME: read studies and/or IDs from list file or files in input folders
STUDIES = ["ACCORD", "OASIS3", "OASIS4", "SHIP"]

rule all:
    input:expand("../../data/NiChart/DX_CO_extrapolate/{study}_DX_AD.csv", study=STUDIES)

rule clin_mri_merge:
    input:
        clinical = "../../data/NiChart/Clinical/{study}_ISTAGING_Clin.csv",
        mri = "../../data/NiChart/MRI/{study}_MasterList_sMRI.csv"
    params:
        variable_name = "Diagnosis",
        study_name = "{study}",
    output:
        combined = "../../data/NiChart/clin_mri_merge/{study}_Diagnosis_mri_clin_combined.csv",
        clean_clinical = "../../data/NiChart/clin_mri_merge/{study}_Diagnosis_cleaned_clinical.csv",
        flag = "../../data/NiChart/clin_mri_merge/{study}_Diagnosis.pkl"
    resources:
        mem_mb=8000
    shell:
        """
        python ./utils/util_clin_mri_merge_v2.py -c {input.clinical} \
                                                 -m {input.mri} \
                                                 -v {params.variable_name} \
                                                 -s {params.study_name} \
                                                 -o1 {output.combined} \
                                                 -o2 {output.clean_clinical} \
                                                 -o3 {output.flag}
        """
rule DX_CO_extrapolate:
    input:
        combined = "../../data/NiChart/clin_mri_merge/{study}_Diagnosis_mri_clin_combined.csv",
        clean_clinical = "../../data/NiChart/clin_mri_merge/{study}_Diagnosis_cleaned_clinical.csv",
        flag = "../../data/NiChart/clin_mri_merge/{study}_Diagnosis.pkl",
        dictionary = "../../resources/Reference/diagnosis_value_mapping.json"
    params:
        variable_name = "Diagnosis",
        variable_type = "DX"
    output:
        "../../data/NiChart/DX_CO_extrapolate/{study}_DX_AD.csv",
    resources:
        mem_mb=8000
    shell:
        """
        python ./utils/util_DX_CO_extrapolate_v2.py -i1 {input.combined}\
                                                    -i2 {input.clean_clinical}\
                                                    -i3 {input.flag}\
                                                    -v {params.variable_name}\
                                                    -vt {params.variable_type}\
                                                    -mp {input.dictionary} \
                                                    -o {output}
        """
