
configfile: "../../config/config.yaml"

localrules: select_sample_spare, merge_rois, copy_model, split_train_test

## Read lists
import pandas as pd

df = pd.read_csv(config["list_studies"])
LIST_STUDIES = df.Study.tolist()

df = pd.read_csv(config["list_rois_primary"])
LIST_ROIS = df.Index.tolist()

#df = pd.read_csv(config["list_SPARE_models"])
#LIST_SPARE_MODELS = df.Model.tolist()


OUT_ROI_TYPES = ['raw', 'normICV']
OUT_MDL_TYPES = ['raw_singleROI_combatAgeSexICV', 
                 'raw_compositeROI_combatAgeSexICV', 
                 'normICV_singleROI_combatAgeSex', 
                 'normICV_compositeROI_combatAgeSex', 
                 'normICV_singleROI_combatAgeSexICV', 
                 'normICV_compositeROI_combatAgeSexICV']
OUT_MDL_TYPES = ['raw_singleROI_combatAgeSexICV', 
                 'normICV_singleROI_combatAgeSex']
OUT_SUFF =  OUT_ROI_TYPES + OUT_MDL_TYPES

## Classification models
LIST_SPARE = ['AD', 'Diabetes', 'Hyperlipidemia', 'Hypertension', 'Obesity', 'Smoking']

## Regression models
SPARE_R_MDL = ['BA']

###################################
## Function definitions

###################################
## Rules
rule ALL:
    #
    ## Rule to run all combinations
    #input:expand("../../models/SPARE/SPARE_{stype}_NiChart_DLMUSE_{dtype}_model.pkl.gz", stype = OUT_SPARE_TYPES, dtype = OUT_SUFF)
    #
    # Rule to run on a single combination as a test
    #input:expand("../../models/SPARE/SPARE_{stype}_NiChart_DLMUSE_{dtype}_model.pkl.gz", stype = ['AD-ISTAG'], dtype = ['normICV_singleROI_combatAgeSex'])
    #
    #
    #input:expand("../../data/SPARE/s_C_{stype}/pred_traintest/NiChart_DLMUSE_{dtype}_pred.csv", stype = SPARE_C_MDL, dtype = OUT_SUFF)
    #input:expand("../../data/SPARE/s_R_{stype}/pred_traintest/NiChart_DLMUSE_{dtype}_pred.csv", stype = SPARE_R_MDL, dtype = OUT_SUFF)
    #
    #
    #input:expand("../../data/SPARE/s{stype}/pred_traintest/NiChart_DLMUSE_{dtype}_pred.csv", stype = SPARE_R_MDL, dtype = OUT_SUFF)
    #input:"../../data/SPARE/sAD/NiChart_DLMUSE_raw_all.csv"
    #input:"../../data/SPARE/sAD/data/NiChart_DLMUSE_raw_train.csv"
    #input:"../../data/SPARE/sAge/data/NiChart_DLMUSE_harmonized_normICV_rsingleROI_hISTAG_train.csv"
    input:"../../data/SPARE/sAge/pred/NiChart_DLMUSE_harmonized_normICV_rsingleROI_hISTAG_pred.csv"
    
    
#################################    
## SPARE

rule merge_demog_and_data:
    '''
    Merge demog and data
    '''
    input:
        demog="../../data/data_consolidated/NiChart_demog.csv",
        data="../../data/data_consolidated/NiChart_DLMUSE_{dtype}.csv",
    params:
        key_var="MRID"
    output:
        "../../data/SPARE/prep/NiChart_DLMUSE+Demog_{dtype}.csv",
    resources:
        mem_mb=8000
    shell:
        "echo python utils/util_merge_two.py {input} {params} {output};"
        "python utils/util_merge_two.py {input} {params} {output}"

rule select_spare_sample:
    '''
    Select spare sample
    - Select samples (from the centiles sample list)
    - Select variables (a set of input variables + ROI names from list)
    '''
    input:
        sample="../../data/samples/sample_SPARE_{stype}_all.csv",
        data="../../data/SPARE/prep/NiChart_DLMUSE+Demog_{dtype}.csv",
        rois="../../config/list_MUSE_singleROI.csv",
    params:
        vars='MRID,Age,Sex',
    output:
        "../../data/SPARE/s{stype}/data/NiChart_DLMUSE_{dtype}_all.csv"
    resources:
        mem_mb=8000
    shell:
        "echo python utils/util_select_sample.py {input} {params} {output}; "
        "python utils/util_select_sample.py {input} {params} {output}"

rule split_train_test:
    '''
    Split spare sample all to train test
    '''
    input:
        "../../data/SPARE/s{stype}/data/NiChart_DLMUSE_{dtype}_all.csv"
    params:
        strat_vars = 'Sex,Target',
        test_ratio = '0.4'
    output:
        "../../data/SPARE/s{stype}/data/NiChart_DLMUSE_{dtype}_train.csv",
        "../../data/SPARE/s{stype}/data/NiChart_DLMUSE_{dtype}_test.csv"        
    resources:
        mem_mb=8000
    shell:
        "echo python utils/util_split_train_test.py {input} {params} {output}; "
        "python utils/util_split_train_test.py {input} {params} {output}"

rule sparesvm_train:
    '''
    Train SPARE model
    '''
    input:
        "../../data/SPARE/s{stype}/data/NiChart_DLMUSE_{dtype}_train.csv"
    params:
        vkey='MRID',
    output:
        "../../data/SPARE/s{stype}/models/NiChart_DLMUSE_{dtype}_model.pkl.gz"
    resources:
        mem_mb=16000
    shell:
        "echo spare_score -a train -i {input} -o {output} -kv {params.vkey} -t {wildcards.stype} "
        "-mt SVM -k linear -pg 1; "
        "spare_score -a train -i {input} -o {output} -kv {params.vkey} -t {wildcards.stype} "
        "-mt SVM -k linear -pg 1"
        
rule sparesvm_test:
    '''
    Test SPARE model using the split test sample
    '''
    input:
        data="../../data/SPARE/s{stype}/data/NiChart_DLMUSE_{dtype}_test.csv",
        mdl="../../data/SPARE/s{stype}/models/NiChart_DLMUSE_{dtype}_model.pkl.gz"
    output:
        csv="../../data/SPARE/s{stype}/pred/NiChart_DLMUSE_{dtype}_pred.csv"
    resources:
        mem_mb=16000
    shell:
        "echo spare_score -a test -i {input.data} -m {input.mdl} -o {output.csv}; "
        "spare_score -a test -i {input.data} -m {input.mdl} -o {output.csv}"

rule sparesvm_eval:
    '''
    Evaluate accuracy on test sample
    '''
    input:
        data="../../data/SPARE/s{stype}/data/NiChart_DLMUSE_{dtype}_test.csv",
        pred="../../data/SPARE/s{stype}/pred/NiChart_DLMUSE_{dtype}_pred.csv"
    output:
        csv="../../data/SPARE/s{stype}/pred/NiChart_DLMUSE_{dtype}_eval.csv"
    resources:
        mem_mb=8000
    shell:
        "echo python utils/util_eval_spare.py {input} {wildcards.stype} {output}; "
        "python utils/util_eval_spare.py {input} {wildcards.stype} {output}"

#rule copy_model:
    #'''
    #Copy model to models folder
    #'''
    #input:
        #"../../data/SPARE/s_{stype}/models/NiChart_DLMUSE_{dtype}_model.pkl.gz"
    #output:
        #"../../models/SPARE/SPARE_{stype}_NiChart_DLMUSE_{dtype}_model.pkl.gz"
    #shell:
        #"cp {input} {output}"
        
#rule copy_spare_scores:
    #'''
    #Copy model to models folder
    #'''
    #input:
        #"../../data/SPARE/s_{stype}/models/NiChart_DLMUSE_{dtype}_model.pkl.gz"
    #output:
        #"../../models/SPARE/SPARE_{stype}_NiChart_DLMUSE_{dtype}_model.pkl.gz"
    #shell:
        #"cp {input} {output}"

