## Import packages
import pandas as pd

# Default config file
configfile: "./config.yaml"

# Read config vars and lists
in_data = config["in_data"]
in_demog = config["in_demog"]
dset_name = config["dset_name"]
out_dir = config["out_dir"]
out_csv = config["out_csv"]
res_dir = config["res_dir"]
centile_vals = config["centile_vals"]
bin_size = config["bin_size"]
sample_cn = f'{res_dir}/{config["sample_centiles_CN"]}'
centile_types = config["centile_types"]

# Set output file names
out_files = [out_csv]
print("Target out files:" + '\n' + '\n'.join(out_files))

# Rules

rule ALL:
    '''
    First rule: lists the final expected out files
    '''
    input: out_files

rule select_rois:
    '''
    Select variables from data
    '''
    input:
        in_csv = in_demog
    params:
        key_col = 'MRID',
        cols_keep = 'MRID,Age',
    output:
        f"{out_dir}/tmp_centiles/sel_vars/{dset_name}_demog.csv"
    resources:
        mem_mb=8000
    shell:
        "python ../../utils/generic/util_select_cols.py {input} {params} {output}"

def get_centiles_sample(wildcards):
    path_centiles = res_dir + '/' + config["sample_centiles_" + wildcards.ctype]
    return path_centiles

rule prepare_sample:
    '''
    Merge demog data to ROIs
    '''
    input:
        sample = get_centiles_sample,
        demog = f"{out_dir}/tmp_centiles/sel_vars/{dset_name}_demog.csv",
        data = in_data
    params:
        key_col = 'MRID'    
    output:
        f"{out_dir}/tmp_centiles/merged/{dset_name}_sample{ctype}.csv"
    resources:
        mem_mb=8000
    shell:
        "python ../../utils/generic/util_merge_dfs_multi.py {output} {params} {input}"


rule calc_centiles:
    input:
        f"{out_dir}/tmp_centiles/merged/{dset_name}_sample{ctype}.csv"
    output:
        f{out_pref} + _sample{ctype}.csv"
    params:
        centile_vals = centile_vals,
        bin_size = bin_size,
    shell:
        "bash ../../utils/centiles/util_calc_centiles.sh {input} {params} {output}"
