## Import packages
import pandas as pd

# Default config file
configfile: "./config.yaml"

# Read config vars and lists
in_data = config["in_data"]
in_demog = config["in_demog"]
dset_name = config["dset_name"]
out_dir = config["out_dir"]
out_csv = config["out_csv"]
res_dir = config["res_dir"]
sample_cn = f'{res_dir}/{config["sample_centiles_CN"]}'

# Set output file names
out_csv = f"{out_dir}/tmp_centiles/merged/{dset_name}_all.csv"
out_files = [out_csv]
print("Target out files:" + '\n' + '\n'.join(out_files))

# Rules

rule ALL:
    '''
    First rule: lists the final expected out files
    '''
    input: out_files

rule select_rois:
    '''
    Select variables from data
    '''
    input:
        in_csv = in_demog
    params:
        key_col = 'MRID',
        cols_keep = 'MRID,Age',
    output:
        f"{out_dir}/tmp_centiles/sel_vars/{dset_name}_demog.csv"
    resources:
        mem_mb=8000
    shell:
        "python ../../utils/generic/util_select_cols.py {input} {params} {output}"

rule prepare_sample:
    '''
    Merge demog data to ROIs
    '''
    input:
        sample = sample_cn,
        demog = f"{out_dir}/tmp_centiles/sel_vars/{dset_name}_demog.csv",
        data = in_data
    params:
        key_col = 'MRID'    
    output:
        f"{out_dir}/tmp_centiles/merged/{dset_name}_all.csv"
    resources:
        mem_mb=8000
    shell:
        "python ../../utils/generic/util_merge_dfs_multi.py {output} {params} {input}"

#def get_centiles_sample(wildcards):
    #path_centiles=res_dir + '/' + config["sample_centiles_" + wildcards.ctype]
    #return path_centiles

rule calc_centiles_single_var:
    input:
        f"../../data/{dir_output}/c_{{centtype}}/data/combined_{{dtype}}_{{ctype}}_all.csv"
    output:
        f"../../data/{dir_output}/c_{{centtype}}/centiles_single/combined_{{dtype}}_{{ctype}}_var{{cvar}}.csv"
    params:
        cent_vals='5,25,50,75,95',
        bin_size='1',
    shell:
        "bash ../../utils/centiles/util_calc_centiles_single.sh {input} {wildcards.cvar} {params} {output}"

#def get_centile_files(wildcards):
    #'''
    #Returns a list of centile csv files for all rois for a specific study
    #'''
    #cent_files = expand(f"../../data/{dir_output}/c_{wildcards.centtype}/centiles_single/combined_{wildcards.dtype}_{wildcards.ctype}_var{{cvar}}.csv", cvar = LIST_VAR)
    #return cent_files

#rule combine_centiles:
    #input:
        #get_centile_files
    #output:
        #f"../../data/{dir_output}/c_{{centtype}}/centiles_combined/combined_{{dtype}}_{{ctype}}_centiles.csv"
    #shell:
        #"bash ../../utils/centiles/util_combine_centiles.sh {output} {input}"

####rule copy_centiles:
    ####input:
        ####"../../data/centiles/centiles-{csample}_combined.csv"
    ####output:
        ####protected("../../models/centiles/centiles-{csample}_combined.csv")
    ####shell:
        ####"bash ./utils/util_combine_centiles.sh {output} {input}"
