## Import packages
import pandas as pd

## Flag to indicate rules that will be run locally (e.g. not submitted to slurm)
##localrules: rename_muse_rois

## Report data
report: "report/workflow.rst"

## Config file
configfile: "../../config/config.yaml"

## Read study list from config
df = pd.read_csv(config["list_studies"])
LIST_STUDIES = df.Study.tolist()

###################################
## Rules

OUT_FILES = expand("../../data/correct_icv/NiChart_{dtype}_{ctype}.csv", dtype = ['MUSE', 'DLMUSE'], ctype = ['normICV', 'percICV'])

rule ALL:
    '''
    First rule: lists the final expected out files
    '''
    input: OUT_FILES

#################################  
## Data preparation

rule select_vars:
    '''
    Select variables from data
    '''
    input:
        in_csv="../../data/data_prep/NiChart_{dtype}.csv",
        dict_csv="../../config/list_MUSE_allROI.csv"
    params:
        dict_var = 'Code',
        vars_list = 'MRID',
    output:
        temp("../../data/correct_icv/prep/NiChart_{dtype}.csv")
    resources:
        mem_mb=8000
    shell:
        "python ../../utils/util_select_vars.py {input} {params} {output}"

rule correct_icv:
    '''
    Normalize ROIs. Values are scaled either by a constant factor (NormICV) or 100 (PercICV)
    '''
    input:
        "../../data/correct_icv/prep/NiChart_{dtype}.csv"
    params:
        icv_var = 'MUSE_702',
        exclude_vars = 'MRID',
        suffix = 'NONE'
    output:
        "../../data/correct_icv/NiChart_{dtype}_{corr_type}.csv"
    resources:
        mem_mb=8000
    shell:
        "python ../../utils/util_corr_icv.py {input} {wildcards.corr_type} {params} {output}"


