'''
Snakemake file for ISTAGING Data Consolidation
 
Input data: MRI and clinical csv files organized as: 
 data/ISTAG_TmpGuray/InitData/{study}{file_suffix}    
'''

## FIXME: read studies and/or IDs from list file or files in input folders
STUDIES = ["ACCORD", "OASIS3", "OASIS4", "SHIP"]

rule all:
#    input:expand("../../data/ISTAG_TmpGuray/InitData/UKBIOBANK-B1/UKBIOBANK-B1_ISTAG.csv", study=STUDIES)
    input:expand("../../data/ISTAG_TmpGuray/DataTables/{study}/{study}_DEMOG.csv", study=STUDIES)
    #input:"../../data/ISTAG_TmpGuray/DataTables/ACCORD/ACCORD_DEMOG.csv"

rule select_sample_ukbb:
    input:
        "../../data/ISTAG_TmpGuray/InitData/UKBIOBANK/UKBIOBANK_sMRI.csv",
    output:
        "../../data/ISTAG_TmpGuray/InitData/UKBIOBANK-B1/UKBIOBANK-B1_sMRI.csv",
    params:
        num_sample = '8000',
    shell:
        "python ./utils/util_subsample_data.py {input} {params} {output}"

rule apply_selection_ukbb:
    input:
        in_csv="../../data/ISTAG_TmpGuray/InitData/UKBIOBANK/UKBIOBANK_{suffix}.csv",
        in_list="../../data/ISTAG_TmpGuray/InitData/UKBIOBANK-B1/UKBIOBANK-B1_sMRI.csv"
    output:
        "../../data/ISTAG_TmpGuray/InitData/UKBIOBANK-B1/UKBIOBANK-B1_{suffix}.csv",
    params:
        key_var = 'MRID',
    shell:
        "python ./utils/util_filter_to_subsampled.py {input} {params} {output}"

VAR_TYPES = ['CLINICAL', 'COG', 'CSF', 'DEMOG', 'DX', 'GENETIC', 'STUDY', 'VISITS']

rule split_tables:
    input:
        "../../data/ISTAG_TmpGuray/InitData/{study}/{study}_ISTAG.csv",
        "../../resources/ISTAG_Dictionaries/dict_short_v2.csv"
    output:
        "../../data/ISTAG_TmpGuray/DataTables/{study}/{study}_CLINICAL.csv",
        "../../data/ISTAG_TmpGuray/DataTables/{study}/{study}_DEMOG.csv",
        "../../data/ISTAG_TmpGuray/DataTables/{study}/{study}_DX.csv",
        "../../data/ISTAG_TmpGuray/DataTables/{study}/{study}_MRI.csv",
        "../../data/ISTAG_TmpGuray/DataTables/{study}/{study}_STUDY.csv"
    params:
        pref="../../data/ISTAG_TmpGuray/DataTables/{study}/{study}",
        tables='CLINICAL,DEMOG,DX,MRI,STUDY'
    resources:
        mem_mb=8000
    shell:
        "python ./utils/util_split_tables.py {input} {params}"
        
